// Auto-generated by sketch.dev/cmd/go2ts.go
// DO NOT EDIT. This file is automatically generated.

export interface ToolCall {
	name: string;
	input: string;
	tool_call_id: string;
	result_message?: AgentMessage | null;
	args?: string;
	result?: string;
}

export interface GitCommit {
	hash: string;
	subject: string;
	body: string;
	pushed_branch?: string;
}

export interface Usage {
	input_tokens: number;
	cache_creation_input_tokens: number;
	cache_read_input_tokens: number;
	output_tokens: number;
	cost_usd: number;
}

export interface AgentMessage {
	type: CodingAgentMessageType;
	end_of_turn: boolean;
	content: string;
	tool_name?: string;
	input?: string;
	tool_result?: string;
	tool_error?: boolean;
	tool_call_id?: string;
	tool_calls?: ToolCall[] | null;
	toolResponses?: AgentMessage[] | null;
	commits?: (GitCommit | null)[] | null;
	timestamp: string;
	conversation_id: string;
	parent_conversation_id?: string | null;
	usage?: Usage | null;
	start_time?: string | null;
	end_time?: string | null;
	elapsed?: Duration | null;
	turnDuration?: Duration | null;
	idx: number;
}

export interface CumulativeUsage {
	start_time: string;
	messages: number;
	input_tokens: number;
	output_tokens: number;
	cache_read_input_tokens: number;
	cache_creation_input_tokens: number;
	total_cost_usd: number;
	tool_uses: { [key: string]: number } | null;
}

export interface State {
	message_count: number;
	total_usage?: CumulativeUsage | null;
	hostname: string;
	working_dir: string;
	initial_commit: string;
	title: string;
	os: string;
	outside_hostname?: string;
	inside_hostname?: string;
	outside_os?: string;
	inside_os?: string;
	outside_working_dir?: string;
	inside_working_dir?: string;
	git_origin?: string;
	outstanding_llm_calls: number;
	outstanding_tool_calls: string[];
	session_id: string;
	ssh_available: boolean;
	ssh_error?: string;
}

export type CodingAgentMessageType = 'user' | 'agent' | 'error' | 'budget' | 'tool' | 'commit' | 'auto';

export type Duration = number;
